/* JawyXDevs style: supplied Horizon/Cosmos hero architecture adapted to a premium black, metallic silver, and electric-blue digital systems studio. */
import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { EffectComposer } from "three/examples/jsm/postprocessing/EffectComposer.js";
import { RenderPass } from "three/examples/jsm/postprocessing/RenderPass.js";
import { UnrealBloomPass } from "three/examples/jsm/postprocessing/UnrealBloomPass.js";
import { ArrowUpRight, ChevronDown } from "lucide-react";

gsap.registerPlugin(ScrollTrigger);

const logo = "/manus-storage/Jawy.devs_7c146be2.jpg";
const title = "CRAFTING HIGH-PERFORMANCE DIGITAL EXPERIENCES THAT SCALE BRANDS WORLDWIDE.";
const words = title.split(" ");

const starVertex = `attribute float size; attribute vec3 color; varying vec3 vColor; uniform float time; uniform float depth; void main(){ vColor=color; vec3 pos=position; float angle=time*.05*(1.-depth*.3); mat2 rot=mat2(cos(angle),-sin(angle),sin(angle),cos(angle)); pos.xy=rot*pos.xy; pos.z=mod(pos.z+time*(34.+depth*22.)+900.,1800.)-900.; vec4 mv=modelViewMatrix*vec4(pos,1.); gl_PointSize=size*(320./max(1.,-mv.z)); gl_Position=projectionMatrix*mv; }`;
const starFragment = `varying vec3 vColor; void main(){ float dist=length(gl_PointCoord-vec2(.5)); if(dist>.5) discard; float alpha=1.-smoothstep(.04,.5,dist); gl_FragColor=vec4(vColor,alpha); }`;

export function JawyxWebGLHero() {
  const containerRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const titleRef = useRef<HTMLHeadingElement>(null);
  const subtitleRef = useRef<HTMLDivElement>(null);
  const progressRef = useRef<HTMLDivElement>(null);
  const menuRef = useRef<HTMLDivElement>(null);
  const [scrollProgress, setScrollProgress] = useState(0);
  const [currentSection, setCurrentSection] = useState(1);
  const [isReady, setIsReady] = useState(false);

  useEffect(() => {
    const container = containerRef.current;
    const canvas = canvasRef.current;
    if (!container || !canvas) return;
    const mobile = window.matchMedia("(max-width: 700px)").matches;
    const reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    const refs = { scene: new THREE.Scene(), camera: new THREE.PerspectiveCamera(75, 1, .1, 2600), renderer: null as THREE.WebGLRenderer | null, composer: null as EffectComposer | null, stars: [] as THREE.Points[], mountains: [] as THREE.Mesh[], nebula: null as THREE.Mesh | null, atmosphere: null as THREE.Mesh | null, raf: 0, scrollTrigger: null as ScrollTrigger | null, target: { x: 0, y: 20, z: 100 }, disposed: false };
    refs.scene.fog = new THREE.FogExp2(0x000810, mobile ? .0005 : .00025);
    refs.camera.position.set(0, 20, 100);
    try { refs.renderer = new THREE.WebGLRenderer({ canvas, antialias: !mobile, alpha: true, powerPreference: "high-performance" }); } catch { container.classList.add("webgl-unavailable"); return; }
    refs.renderer.setPixelRatio(Math.min(window.devicePixelRatio, mobile ? 1.25 : 1.8)); refs.renderer.toneMapping = THREE.ACESFilmicToneMapping; refs.renderer.toneMappingExposure = .62; refs.renderer.setClearColor(0x000000, 0);
    refs.composer = new EffectComposer(refs.renderer); refs.composer.addPass(new RenderPass(refs.scene, refs.camera)); if (!mobile && !reducedMotion) refs.composer.addPass(new UnrealBloomPass(new THREE.Vector2(1,1), .72, .4, .82));

    const createStars = () => { const count = mobile ? 850 : 5000; for (let layer = 0; layer < 3; layer++) { const positions = new Float32Array(count * 3); const colors = new Float32Array(count * 3); const sizes = new Float32Array(count); for (let i=0;i<count;i++) { const radius=200+Math.random()*800; const theta=Math.random()*Math.PI*2; const phi=Math.acos(Math.random()*2-1); positions[i*3]=radius*Math.sin(phi)*Math.cos(theta); positions[i*3+1]=radius*Math.sin(phi)*Math.sin(theta); positions[i*3+2]=radius*Math.cos(phi)-layer*220; const blue=Math.random()>.76; const c=new THREE.Color(blue?0x159dff:0xdbe8f4); colors[i*3]=c.r; colors[i*3+1]=c.g; colors[i*3+2]=c.b; sizes[i]=.55+Math.random()*(blue?1.8:1.2); } const g=new THREE.BufferGeometry(); g.setAttribute("position",new THREE.BufferAttribute(positions,3)); g.setAttribute("color",new THREE.BufferAttribute(colors,3)); g.setAttribute("size",new THREE.BufferAttribute(sizes,1)); const m=new THREE.ShaderMaterial({ uniforms:{time:{value:0},depth:{value:layer}}, vertexShader:starVertex, fragmentShader:starFragment, transparent:true, blending:THREE.AdditiveBlending, depthWrite:false }); const stars=new THREE.Points(g,m); refs.scene.add(stars); refs.stars.push(stars); } };
    const createNebula = () => { const g=new THREE.PlaneGeometry(8000,4000,80,40); const m=new THREE.ShaderMaterial({ uniforms:{time:{value:0},color1:{value:new THREE.Color(0x0033aa)},color2:{value:new THREE.Color(0x159dff)}}, vertexShader:`varying vec2 vUv; uniform float time; void main(){vUv=uv; vec3 p=position; p.z+=sin(p.x*.01+time)*cos(p.y*.01+time)*20.; gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`, fragmentShader:`varying vec2 vUv; uniform vec3 color1; uniform vec3 color2; uniform float time; void main(){float f=sin(vUv.x*10.+time)*cos(vUv.y*10.+time)*.5+.5; vec3 c=mix(color1,color2,f); float a=.28*(1.-length(vUv-.5)*2.); gl_FragColor=vec4(c,a);}`, transparent:true, blending:THREE.AdditiveBlending, side:THREE.DoubleSide, depthWrite:false }); refs.nebula=new THREE.Mesh(g,m); refs.nebula.position.z=-1050; refs.scene.add(refs.nebula); };
    const createMountains = () => { const layers=[[-50,60,0x07111d,1],[-100,80,0x0a2034,.8],[-150,100,0x0b3859,.6],[-200,120,0x0b527c,.4]] as const; layers.forEach(([z,height,color,opacity],index)=>{ const pts:THREE.Vector2[]=[]; const segments=mobile?28:50; for(let i=0;i<=segments;i++){const x=(i/segments-.5)*1000; const y=Math.sin(i*.1)*height+Math.sin(i*.05)*height*.5+Math.random()*height*.2-100; pts.push(new THREE.Vector2(x,y));} pts.push(new THREE.Vector2(5000,-300),new THREE.Vector2(-5000,-300)); const g=new THREE.ShapeGeometry(new THREE.Shape(pts)); const m=new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide,depthWrite:false}); const mesh=new THREE.Mesh(g,m); mesh.position.set(0,z===-50?z/2:z/2,z); mesh.userData={baseZ:z,baseY:z===-50?z/2:z/2,index}; refs.scene.add(mesh); refs.mountains.push(mesh); }); };
    const createAtmosphere = () => { const g=new THREE.SphereGeometry(mobile?420:600,mobile?24:42,mobile?18:28); const m=new THREE.ShaderMaterial({uniforms:{time:{value:0}},vertexShader:`varying vec3 n; void main(){n=normalize(normalMatrix*normal); gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec3 n; uniform float time; void main(){float e=pow(.7-dot(n,vec3(0.,0.,1.)),2.); float pulse=.9+sin(time*2.)*.1; vec3 c=vec3(.03,.36,1.)*e*pulse; gl_FragColor=vec4(c,e*.28);}`,side:THREE.BackSide,blending:THREE.AdditiveBlending,transparent:true}); refs.atmosphere=new THREE.Mesh(g,m); refs.atmosphere.position.set(260,10,-420); refs.scene.add(refs.atmosphere); };
    createStars(); createNebula(); createMountains(); createAtmosphere();
    const blueLight=new THREE.PointLight(0x159dff,5,600); blueLight.position.set(220,80,-120); refs.scene.add(blueLight); const silverLight=new THREE.PointLight(0xd9e9f5,2.5,500); silverLight.position.set(-160,120,-90); refs.scene.add(silverLight); refs.scene.add(new THREE.AmbientLight(0x59758b,1.1));
    const pointer={x:0,y:0}; const onPointer=(e:PointerEvent)=>{if(mobile)return; pointer.x=(e.clientX/window.innerWidth-.5)*2; pointer.y=(e.clientY/window.innerHeight-.5)*2;}; window.addEventListener("pointermove",onPointer,{passive:true});
    const cameraPositions=[{x:0,y:30,z:300},{x:4,y:38,z:-180},{x:-6,y:52,z:-1250}];
    const updateScroll=(progress:number)=>{ const scaled=progress*2; const section=Math.min(1,Math.floor(scaled)); const local=scaled-section; const from=cameraPositions[section]; const to=cameraPositions[section+1]??from; const eased=local*local*(3-2*local); refs.target.x=THREE.MathUtils.lerp(from.x,to.x,eased); refs.target.y=THREE.MathUtils.lerp(from.y,to.y,eased); refs.target.z=THREE.MathUtils.lerp(from.z,to.z,eased); refs.camera.fov=THREE.MathUtils.lerp(75,mobile?58:43,progress); refs.camera.updateProjectionMatrix(); setScrollProgress(progress); setCurrentSection(Math.min(2,Math.floor(progress*3)+1)); };
    const scrollTrigger=ScrollTrigger.create({trigger:document.body,start:"top top",end:"bottom bottom",scrub:1.15,onUpdate:self=>updateScroll(self.progress)}); refs.scrollTrigger=scrollTrigger;
    const resize=()=>{if(!refs.renderer||!refs.composer)return; const w=window.innerWidth,h=window.innerHeight; refs.camera.aspect=w/h; refs.camera.updateProjectionMatrix(); refs.renderer.setSize(w,h,false); refs.composer.setSize(w,h);}; resize(); window.addEventListener("resize",resize); updateScroll(0);
    const animate=(time:number)=>{if(refs.disposed)return; const t=time*.001; refs.stars.forEach((s,i)=>{(s.material as THREE.ShaderMaterial).uniforms.time.value=t;s.rotation.z=t*.008*(i+1);}); if(refs.nebula)(refs.nebula.material as THREE.ShaderMaterial).uniforms.time.value=t*.5; if(refs.atmosphere)(refs.atmosphere.material as THREE.ShaderMaterial).uniforms.time.value=t; refs.mountains.forEach((m,i)=>{m.position.x=Math.sin(t*.1+i)*3*(i+1)+pointer.x*(8+i*8);m.position.y=(m.userData.baseY as number)+Math.cos(t*.15+i)*(1+i)+pointer.y*(i+1)*2;}); if(refs.nebula){refs.nebula.position.x=80+Math.sin(t*.12)*28+pointer.x*14;refs.nebula.position.y=30+Math.cos(t*.1)*14+pointer.y*8;} if(refs.atmosphere){refs.atmosphere.position.x=260+Math.sin(t*.16)*24+pointer.x*12;refs.atmosphere.position.y=10+Math.cos(t*.12)*12+pointer.y*8;} refs.camera.position.x+=(refs.target.x+pointer.x*5-refs.camera.position.x)*.045; refs.camera.position.y+=(refs.target.y-pointer.y*3-refs.camera.position.y)*.045; refs.camera.position.z+=(refs.target.z-refs.camera.position.z)*.045; const travel=Math.min(1,Math.max(0,(300-refs.camera.position.z)/1550)); refs.stars.forEach((s,i)=>{s.position.z=THREE.MathUtils.lerp(0,-travel*(80+i*45),.35); s.scale.setScalar(1+travel*(i+1)*.08);}); if(refs.nebula){refs.nebula.scale.setScalar(1+travel*.22); refs.nebula.position.z=-1050+travel*120;} if(refs.atmosphere)refs.atmosphere.scale.setScalar(1+travel*.16); refs.camera.lookAt(pointer.x*12,pointer.y*4,-600); refs.composer?.render(); refs.raf=requestAnimationFrame(animate);}; refs.raf=requestAnimationFrame(animate); setIsReady(true);
    return()=>{refs.disposed=true;cancelAnimationFrame(refs.raf);refs.scrollTrigger?.kill();window.removeEventListener("pointermove",onPointer);window.removeEventListener("resize",resize);refs.stars.forEach(s=>{s.geometry.dispose();(s.material as THREE.Material).dispose();});refs.mountains.forEach(m=>{m.geometry.dispose();(m.material as THREE.Material).dispose();});if(refs.nebula){refs.nebula.geometry.dispose();(refs.nebula.material as THREE.Material).dispose();}if(refs.atmosphere){refs.atmosphere.geometry.dispose();(refs.atmosphere.material as THREE.Material).dispose();}refs.renderer?.dispose();refs.composer?.dispose();};
  }, []);

  useEffect(() => { if(!isReady)return; const ctx=gsap.context(()=>{if(menuRef.current)gsap.from(menuRef.current,{x:-80,opacity:0,duration:1,ease:"power3.out"}); if(titleRef.current){const chars=titleRef.current.querySelectorAll(".title-char");gsap.from(chars,{y:180,opacity:0,duration:1.25,stagger:.018,ease:"power4.out",delay:.25});} if(subtitleRef.current)gsap.from(subtitleRef.current.querySelectorAll(".subtitle-line"),{y:40,opacity:0,duration:.8,stagger:.14,ease:"power3.out",delay:.8}); if(progressRef.current)gsap.from(progressRef.current,{opacity:0,y:30,duration:.8,delay:1});}); return()=>ctx.revert(); }, [isReady]);

  return <div ref={containerRef} className="hero-container cosmos-style"><canvas ref={canvasRef} className="hero-canvas" /><div ref={menuRef} className="side-menu"><img src={logo} alt="JawyXDevs logo" /><span className="vertical-text">JAWYXDEVS // SYSTEMS</span></div><div className="hero-content cosmos-content"><p className="hero-kicker">ELITE WEB ENGINEERING STUDIO</p><h1 ref={titleRef} className="hero-title">{words.map((word,i)=><span key={`${word}-${i}`} className="title-word">{word.split("").map((char,j)=><span key={`${char}-${j}`} className="title-char">{char}</span>)}{i<words.length-1&&<span className="title-space">&nbsp;</span>}</span>)}</h1><div ref={subtitleRef} className="hero-subtitle cosmos-subtitle"><p className="subtitle-line">Interactive digital systems for brands with ambition.</p><p className="subtitle-line">Premium engineering, motion, and atmosphere in one continuous world.</p></div><div className="hero-actions codebase-actions"><a href="#work" className="button button-primary">VIEW OUR WORK <ArrowUpRight size={16}/></a><a href="#contact" className="button button-ghost">START A PROJECT <ArrowUpRight size={16}/></a></div></div><div ref={progressRef} className="scroll-progress"><span className="scroll-text">SCROLL</span><span className="progress-track"><span className="progress-fill" style={{width:`${scrollProgress*100}%`}}/></span><strong>{String(currentSection).padStart(2,"0")} / 03</strong><ChevronDown size={14}/></div><div className="cosmos-meta">EST. / 2024 <i>TORONTO · WORLDWIDE</i></div></div>;
}
